### ISSUE TITLE
QXcbConnection: XCB error: 13

### ISSUE THREAD

**Issue by LeonardoRez** [MISTLab/DOOR-SLAM#3]
I'm trying to run the simulation, but it keeps aborting with this message: 

QXcbConnection: XCB error: 13 (BadGC), sequence: 615, resource id: 0, major code: 72 (PutImage), minor code: 0
vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)

the sequence varies, but the rest was the same in all tries. Am I supposed to configure something between running the command line and hitting the "play experiment" button?

Thanks in advance!

**Comment by lajoiepy** [comment]
Hi! Thanks for your interest in DOOR-SLAM :)

Do you get this error when you launch the x11docker command?

The problem might be related to the configuration options. I suggest that you take a look at the x11docker documentation to see what best suits your system : https://github.com/mviereck/x11docker . My guess is that the problem is related to the "X server and Wayland Options" ( see: https://github.com/mviereck/x11docker/wiki/X-server-and-Wayland-Options ).

Note that although we use x11docker, this is not mandatory. Since the simulation requires some tricky installation details, we packaged it in a Docker image to ease its reuse. However, it has the drawback that you need to share the X Server between the Docker container and the host machine to see the simulation. You can do this in a number of different ways other than x11docker depending on your local setup. I suggest you take a look at this http://fabiorehm.com/blog/2014/09/11/running-gui-apps-with-docker/ .

I hope this will solve your problem!

**Comment by LeonardoRez** [comment]
Hello, Pierre! The paper looks really cool!

No, I get this error after starting the simulation. It runs for a few seconds, and then closes, leaving the message from above in the docker container. In the terminal running the x11docker no error message is shown.

The print shows the x11docker window on the left and the ARGoS inside the docker container on the right
![image](https://user-images.githubusercontent.com/13459436/86818299-96ef2280-c05c-11ea-9b2e-ddf40bef1820.png)

Could I be doing it wrong? I'm supposed to run the x11docker command in one bash and then running the docker exec in another one, right?

Thank you for your attention!

**Comment by beltrame** [comment]
It looks like some error in the GUI libraries. What system are you running this on?

**Comment by LeonardoRez** [comment]
An ubuntu 18.04 LTS

**Comment by lajoiepy** [comment]
Ok, I think I found the solution.
After tinkering a lot with my own configuration, I managed to reproduce the bug and it seems to be a permissions issue.
The code should create a folder named `datasets` inside the HOST_FOLDER (used for logs) that is shared with the container, but this seems to fail in your case.
So, for now, I suggest you create that folder (`datasets`) manually inside your log folder. I updated the documentation about this.
Please, let me know if it solves the issue.
Thanks!

**Comment by LeonardoRez** [comment]
It worked! Thank you very much
