### ISSUE TITLE
How could I set up the 3 robot SLAM?

### ISSUE THREAD

**Issue by yeweihuang** [MISTLab/DOOR-SLAM#4]
Hi, the 3 robot experiment you show in your ICRA paper is impressive, but it seems that there are only launch file for two robots in the multi_distributed_SLAM_module. Could you please also release the launch file for 3 robots, or is there any method to reach the 3 robot result with the present code?

**Comment by lajoiepy** [comment]
Hi! Thanks for your interest in DOOR-SLAM!

As mentionned in the paper, our online field experiments were conducted with 2 robots. We also did an offboard experiment with 3 TX2s on the KITTI00 sequence. 

To perform it, first you have to download the sequence and split it into 3 parts (you can do this using the `rosbag filter` command, look [here](http://wiki.ros.org/rosbag/Commandline) ). 

Then, instead of using the Intel camera topics as input, you have to use the sequence parts bags topics (you can find an example of this [here](https://github.com/bramtoula/multi_robot_SLAM_separators/blob/2ce1fa45107e92bde5329d023565cf5eebe26004/ros_ws/src/multi_robot_separators/launch/kitti_example.launch) , look closely at the `<!-- Play the bag within the namespace -->` section). 

Then, you will have to adjust the `local_robot_id` and `other_robot_id` according to your 3 robots setup. In our practical implementation we did not implement a neighbor discovery mechanism (this is a complex problem in itself, that we simulate in the ARGoS simulation). So, you need to specify the robot neighbor (`other_robot_id`). I suggest the following setup: 
|     Robot      | `local_robot_id`  | `other_robot_id`  |
|---|---|---|
| Robot 0   | 0                 | 1                 |
| Robot 1   | 1                 | 2                 |
| Robot 2   | 2                 | 0                 |

Quick final note: TX2s have very limited memory so adding a KITTI sequence onboard (~4GB) that need to be loaded to RAM is very detremental to the system performance compared to using a camera. Therefore, I suggest you to run the bag at a much slower frame rate ( look [here](http://wiki.ros.org/rosbag/Commandline) ).

**Comment by yeweihuang** [comment]
Great! This is exactly what I want to know! Thank you for your help!
