### ISSUE TITLE
Question about testing on KITTI

### ISSUE THREAD

**Issue by bnblzq** [MISTLab/DOOR-SLAM#7]
hello, 
   I've read your paper, in which you mentioned your project has been tested on KITTI, but as far as I know,  KITTI only provides with one trajectory(one car perspective). Would you mind teaching me how to build multi vechiles(drones) method, or just manully split the whole rosbag into serveral parts with overlapping area ?

Thank u for ur attention~

**Comment by lajoiepy** [comment]
Hi!
You got it, the idea is to split manually the rosbag while making sure to have some overlaps. 
How to split a rosbag : https://answers.ros.org/question/99711/how-to-split-a-recorded-rosbag-file/
In the case of KITTI00 splitting it into roughly 3 equal parts should give you overlapping sections due to the large number of loop closures in the dataset. Otherwise, just make sure that in each rosbag section there is at least one loop closure with another section. Otherwise you will get a disconnected pose graph.
