### ISSUE TITLE
Question in launching container

### ISSUE THREAD

**Issue by b573708832** [MISTLab/DOOR-SLAM#8]
Hello!
I have read your paper and try to run multi-robot slam simulation. When i follow the step 2--launch container from https://mistlab.ca/DOOR-SLAM/simulation.html, it seems stuck at mid of somewhere. 
![question](https://user-images.githubusercontent.com/80692499/111159226-d69ae080-85d3-11eb-9fc5-9fbc35e28d71.png)
After "x11docker note: Found 'WORKDIR /home/docker/robust_distributed_slam_simulation/argos_simulation' in image.  
  You can change it with option --workdir=DIR.", the program doesn't seem run anymore or it's stuck. Which step may i had mistakes? And what should i do now? Thanks for your reply!!!!

**Comment by lajoiepy** [comment]
Hi thanks for your interest! 
You are right about the `--workdir` parameter, the documentation with respect to x11docker is currently a bit outdated. 
Otherwise I don't think there are any other problems here. The x11docker command does not launch a terminal in the container, it only starts the container. 
To launch the simulation experiment, you need to first connect to the container with something like: `docker exec -it YOUR_CONTAINER_ID bash` and then, from this terminal, execute the bash commands as explained in the documentation.
Hope it solves your problem!

**Comment by b573708832** [comment]
Oh! Problem solved! Thanks for your quickly reply! Thank you VERY much! :)
